[Application]
AutoCopyToClipboardNewCaptures=true
HideMainWindowDuringScreenshot=false
SaveDirectory=/home/deboost
StartMinimizedToTray=true

[ImageGrabber]
LastRectArea=@Rect(857 387 27 323)
ShowMainWindowAfterTakingScreenshotEnabled=false

[KImageAnnotator]
ToolFont_1=@Variant(\0\0\0@\0\0\0\x10\0\x46\0r\0\x65\0\x65\0S\0\x61\0n\0s@.\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)

[MainWindow]
Position=@Point(963 553)

[recentImagesPath]
1\imagePath=/home/deboost/.config/awesome/pic/lily58_thai.png
2\imagePath=/home/deboost/ksnip_20221019-170825.png
3\imagePath=/home/deboost/ksnip_20221019-171037.png
4\imagePath=/home/deboost/ksnip_20221019-171039.png
5\imagePath=/home/deboost/ksnip_20221019-171040.png
6\imagePath=/home/deboost/d/recruit/5nn_score.png
size=6
