[Application]
AutoCopyToClipboardNewCaptures=true
SaveDirectory=/home/deboost
StartMinimizedToTray=true

[ImageGrabber]
LastRectArea=@Rect(0 0 1919 1076)

[KImageAnnotator]
ToolFont_1=@Variant(\0\0\0@\0\0\0\x10\0\x46\0r\0\x65\0\x65\0S\0\x61\0n\0s@.\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)

[MainWindow]
Position=@Point(963 27)

[recentImagesPath]
1\imagePath=/home/deboost/.config/awesome/pic/lily58_thai.png
size=1
